name: Deploy Resume

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload website files
        run: |
          az storage blob upload-batch \
            --account-name resumerg9ec1 \
            --destination '$web' \
            --source . \
            --overwrite \
            --auth-mode login
