name: Deploy Resume
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show Azure account
        run: az account show

      - name: Upload website files
        run: |
          az storage blob upload \
            --account-name resumerg9ec1 \
            --container-name '$web' \
            --file index.html \
            --name index.html \
            --overwrite true \
            --auth-mode login
