name: Deploy Resume to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload index.html to Azure
        uses: azure/storage-blob-upload@v1
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container-name: '$web'
          source: './index.html'
          destination-path: 'index.html'
